version: '2'

messages:
  $i18n: locales.yml

template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![Image showing preview of the toolchain](toolchain.jpg)'
  icon: icon.svg
  required:
    - repo
    - build
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"

toolchain:
  name: poultrysense-bts-ingest-{{timestamp}}
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"

services:
  repo:
    service_id: >
      $env.source_provider ? $env.source_provider : 'githubpublic'
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: >
        $env.type === 'link' ? 
          $env.app_repo : 'https://github.com/sberajaw/poultrysense-bts-ingest'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ? 
          $env.app_repo : 'https://github.com/sberajaw/poultrysense-bts-ingest'
      type: $env.type || 'clone'
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services: 
        - repo
      name: "{{services.repo.parameters.repo_name}}"
      ui-pipeline: false
      configuration:
        content: 
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          REGION_ID: "{{form.pipeline.parameters.dev-region}}"
          ORGANIZATION: "{{form.pipeline.parameters.dev-organization}}"
          SPACE: "{{form.pipeline.parameters.dev-space}}"
          DEPLOYER_API_KEY: "{{form.pipeline.parameters.api-key}}"
          ICF_NAMESPACE: "{{form.pipeline.parameters.icf-namespace}}"
          ICF_NAMESPACE_ID: "{{form.pipeline.parameters.icf-namespace-id}}"
          POULTRY_SENSE_HOST: "{{form.pipeline.parameters.poultry-sense-host}}"
          POULTRY_SENSE_USERNAME: "{{form.pipeline.parameters.poultry-sense-username}}"
          POULTRY_SENSE_PASSWORD: "{{form.pipeline.parameters.poultry-sense-password}}"
          BTS_HOST: "{{form.pipeline.parameters.bts-host}}"
          BTS_ORG_ID: "{{form.pipeline.parameters.bts-org-id}}"
          BTS_ORG_PREFIX: "{{form.pipeline.parameters.bts-org-prefix}}"
          BTS_ORG_HQ_GLN: "{{form.pipeline.parameters.bts-org-hq-gln}}"
          BTS_API_KEY: "{{form.pipeline.parameters.bts-api-key}}"
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      dev-region: "{{deploymentRegion}}"
      dev-organization: "{{deploymentOrg}}"
      dev-space: "{{deploymentSpace}}"
      api-key: "{{api-key}}"
      fn-package: "{{fn-package}}"
      icf-namespace: "poultrysense-bts-ingest"
      icf-namespace-id: "8adb40c2-ece0-44c8-b03a-15a93a9b631f"
      poultry-sense-host: "http:\/\/ec2-3-226-77-248.compute-1.amazonaws.com:3000"
      poultry-sense-username: "Mick@prognostix-poultry.com"
      poultry-sense-password: "{{poultrySensePassword}}"
      bts-host: "food.ibm.com"
      bts-org-id: "01d3e95f-b3e5-40b1-835b-cdc13f7ef937"
      bts-org-prefix: "2343234"
      bts-org-hq-gln: "2343234000001"
      bts-api-key: "{{btsApiKey}}"

